(() => {
  const data=window.PENGU_DEMO,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const panels={brief:$("#briefPanel"),outline:$("#outlinePanel"),generate:$("#generatePanel"),compare:$("#comparePanel"),essay:$("#essayPanel")};
  const labels={brief:["01 / INPUT","写作任务"],outline:["02 / OUTLINE SET","大纲路线"],generate:["03 / GENERATION","生成过程"],compare:["04 / BATCH REVIEW","候选比较"],essay:["05 / SELECTED DRAFT","完整成品"]};
  let selectedOutline=null,running=false;
  function toast(text){const t=$("#toast");t.textContent=text;t.classList.remove("is-hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add("is-hidden"),2200)}
  function showPanel(name){Object.entries(panels).forEach(([key,node])=>node.classList.toggle("is-hidden",key!==name));$$('[data-panel]').forEach(b=>b.classList.toggle("is-active",b.dataset.panel===name));$("#panelCode").textContent=labels[name][0];$("#panelTitle").textContent=labels[name][1];window.scrollTo({top:0,behavior:"smooth"})}
  function renderOutlines(){$("#outlineGrid").innerHTML=data.outlines.map(o=>`<article class="outline-card ${selectedOutline===o.id?'is-selected':''}" data-outline="${o.id}"><span>${o.tag}</span><em>${o.score}</em><h2>${o.title}</h2><p>${o.summary}</p><ol>${o.points.map(p=>`<li>${p}</li>`).join("")}</ol></article>`).join("");$$('[data-outline]').forEach(card=>card.addEventListener("click",()=>{selectedOutline=card.dataset.outline;renderOutlines();const chosen=data.outlines.find(o=>o.id===selectedOutline);$("#outlineChoiceText").textContent=`已选择：${chosen.title}`;$("#chooseOutline").disabled=false}))}
  function renderCandidates(){$("#candidateGrid").innerHTML=data.candidates.map(c=>`<article class="candidate-card ${c.id===4?'is-best':''}"><header><span>${String(c.id).padStart(2,"0")}</span><h3>${c.title}</h3><b>${c.score}</b></header><blockquote>${c.opening}</blockquote><div class="score-row"><span>结构 ${c.structure}</span><span>声音 ${c.voice}</span><span>风险 ${c.risk}</span></div><p>${c.note}</p></article>`).join("")}
  function renderEssay(){$("#essayTitle").textContent=data.essay.title;$("#essaySubtitle").textContent=data.essay.subtitle;$("#essayBody").innerHTML=data.essay.sections.map(s=>`<section><h2>${s.h}</h2><p>${s.p}</p></section>`).join("")}
  function runGeneration(){if(running)return;running=true;$("#startGeneration").disabled=true;const steps=[{p:12,x:8,msg:"建立四个开口种子"},{p:28,x:26,msg:"锁定荒诞路线与事实边界"},{p:48,x:47,msg:"生成六份同题初稿"},{p:68,x:66,msg:"检查动物学断言与拟人化风险"},{p:84,x:82,msg:"统一比较结构与声音"},{p:100,x:92,msg:"候选 04 成为演示成品"}];let i=0;$("#generationLog").innerHTML="";const next=()=>{const s=steps[i];$("#generationPercent").textContent=`${s.p}%`;$("#generationFill").style.width=`${s.p}%`;$("#skater").style.left=`${s.x}%`;$("#generationLog").insertAdjacentHTML("beforeend",`<li>${s.msg}</li>`);i++;if(i<steps.length)setTimeout(next,620);else setTimeout(()=>{running=false;toast("六份候选已完成统一评分");showPanel("compare")},800)};next()}
  $("#taskInput").value=data.task;renderOutlines();renderCandidates();renderEssay();
  $$('[data-panel]').forEach(b=>b.addEventListener("click",()=>showPanel(b.dataset.panel)));$$('[data-go]').forEach(b=>b.addEventListener("click",()=>showPanel(b.dataset.go)));
  $("#chooseOutline").addEventListener("click",()=>showPanel("generate"));$("#startGeneration").addEventListener("click",runGeneration);$("#modeButton").addEventListener("click",()=>{document.body.classList.toggle("night");$("#modeButton").textContent=document.body.classList.contains("night")?"DAY":"NIGHT"});$("#copyDemo").addEventListener("click",()=>toast("静态演示：正文复制动作未写入剪贴板"));
})();
