// Shared client state. Domain modules own behavior; this module only holds values.
export const state = {
  projects: [],
  profiles: [],
  activeProject: null,
  chapters: [],
  wishes: [],
  messages: [],
  selectedChapter: null,
  pendingChapterSelection: null,
  renderedChapterKey: null,
  selectedProfileId: "mock",
  sourceFile: null,
  sources: [],
  sourceMode: "upload",
  selectedSourceId: null,
  wizardStep: 1,
  ideas: [],
  draftProjectId: null,
  brief: null,
  preparation: null,
  modelView: "space",
  modelRotation: { x: -0.42, y: 0.68 },
  outlineLayout: "parallel",
  activeTask: null,
  pollTimer: null,
  wizardIntroTimer: null,
  editing: false,
  chapterFilter: "all",
  readingFocus: false,
  readingTheme: "warm",
  readingFont: "song",
  readingFontSize: 18,
  readingLineWidth: 700,
  readingTone: "deep",
  readingPaperColor: "#f8f3e8",
  readingInkColor: "#27333d",
  bookRun: null,
  bookEstimate: null,
  bookRunError: null,
  bookRunCompact: false,
  spoilerOutlineView: null,
  relationshipMap: null,
  relationshipContinuity: null,
  relationshipViewChapter: null,
  relationshipExpanded: new Set(),
  relationshipViewport: { x: 0, y: 0, scale: 1 },
  relationshipPanEnabled: false,
  selectedRelationshipNodeId: null,
  selectedRelationshipEdgeIndex: null,
  outlineUnsealed: false,
  spoilerGateStep: 0,
  spoilerChallenge: null,
  selectedCausalNodeId: null,
  outlineChangeProposal: null,
  pendingDeletion: null,
  sourceImportFromManager: false,
  sourcePollTimer: null,
  libraryError: null,
  projectRefreshError: null,
  preparationError: null,
  relationshipContinuityError: null,
  relationshipChapterRequestSerial: 0,
  wizardWaitTimer: null,
  wizardWaitStartedAt: 0,
  rawRequirementsExpanded: false,
  clarificationDrafts: new Map(),
  receiptCastView: "primary",
  aestheticGuidanceNotified: new Set()
};
